server:
  port: 8080

spring:
  application:
    name: scheduler
  datasource:
    url: jdbc:h2:mem:scheduler;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
app:
  scheduling:
    work-hours:
      start: "09:00" # local working-hours policy (UTC-based for now)
      end: "17:00"
    buffer-minutes: 15
    granularity-minutes: 5
    weights:
      earlier-better: 1.0
      within-working-hours: 0.5
      small-gaps-penalty: 0.75